### ISSUE TITLE
[Meta] [Sozialpass] Provide the app in english

### ISSUE THREAD

**Issue by steffenkleinle** [digitalfabrik/entitlementcard#1174]
As a user i want to be able to switch the language to english.

## Acceptance Criteria:
 - implement a button to switch the language from german to english and back

## Technical Tasks:
 - [x] Setup i18n/l10n: #904
 - [x] Implement a switch for the app language #1175
 - [x] Provide labels in English #1178
 - [x] Make this feature configureable via buildConfig to use it only for sozialpass #1176
 - [x] Translate the build configs #1177

**Deadline 30.11.2023**

## Additonal information:
Bereitstellung der App auf Englisch
• Die App Nürnberg-Pass kann über das Menü von Deutsch auf Englisch (oder
andersherum) umgestellt werden
• Die Übersetzungen sind im Angebot inkludiert, betreffen lediglich die AppKonstanten und keine Daten von Akzeptanzpartnern.
• Die initial voreingestellte Sprache richtet sich nach der Systemsprache des
Smartphones:
o Systemsprache Deutsch: Deutsch als Sprache für App Nürnberg-Pass
vorausgewählt
o Systemsprache Nicht-Deutsch: Englisch als Sprache für App NürnbergPass vorausgewählt

**Comment by f1sh1918** [comment]
all issues are resolved :)
