### ISSUE TITLE
Add validation to importAcceptingStores mutation in the backend

### ISSUE THREAD

**Issue by seluianova** [digitalfabrik/entitlementcard#1644]
**Is your feature request related to a problem? Please describe.**
Follow up for #1571

Currently we have csv validation on the administration side, but no validation on the backend.
This means that if the request is sent directly to the backend, our validation rules can be violated.

For example:

In the administration we check that the mandatory fields are not null (name, street, houseNumber, postalCode, location).
But with a direct request to the backend I can create a store with a null-name.

Or:
We validate in the administration, that the categoryId refers to the current project.
But in the backend I can save a store with any existing category id.

Or:
In the administration we check duplicates by name & address.
But the backend allows to create a store with the same name & address, but with a difference in some other fields (like a different description, for example), because in the backend we only consider 2 records as duplicates if they are completely the same.

**Describe the solution you'd like**
Add csv validation to the importAcceptingStores mutation

**TODO**:

- [x] check that mandatory fields are not blank: name, street, houseNumber, postalCode, location, coordinates
- [ ] check that the categoryId refers to the current project
- [x] unify working with duplicates
- [x] clean data (remove trailing whitespaces)

**Describe alternatives you've considered**
Alternatively we could move the validation entirely to the backend (in order not to implement validation 2 times).
If validation errors occur, they can be returned from the backend in the response and displayed in the administration.

**Comment by seluianova** [comment]
Also we don't "clean" data in the backend (remove trailing spaces)
Probably this should be moved from administration component to the backend.

**Comment by seluianova** [comment]
Why "street" in the database is nullable, but in the administration this field is mandatory for Nürnberg?

Do we want to create separate validation rules for each project in the backend like in the admistration? 
Maybe the rules like mandatory and optional fields should be the same for all projects.

**Comment by connium** [comment]
For CSV the fields are mandatory. For the XML import we are not sure whether these fields are filled.

**Comment by seluianova** [comment]
> check that the categoryId refers to the current project

We don't have this check in the current import process, because we don't store the mapping between projects and categories in the backend.
But we configure that separately in the administration and in the frontend module.
We probably need to store this data in one place, for example, in the backend, so that other components could query that from the backend.
